### ISSUE TITLE
API v2

### ISSUE THREAD

**Issue by tuxd** [NarHakobyan/ngx-linkedIn#1]
Hi,

I don't seem to be getting any logging after signing in, could it be that it is using v1 of the linkedin API and not v2? How can I change it to v2?

**Comment by NarHakobyan** [comment]
Hi @tuxd, does your issue still exist?

**Comment by tuxd** [comment]
Yeah it does, but maybe I've messed up something else, like the redirect URL. I get this error:

api.linkedin.com/v1/people/~?oauth_token=VjXSq40y5VTJGgFMBMYUpfm40CAfID0AI4hN:1 Failed to load resource: the server responded with a status of 401 ()
api.linkedin.com/v1/people/~?oauth_token=VjXSq40y5VTJGgFMBMYUpfm40CAfID0AI4hN:1 Failed to load resource: the server responded with a status of 401 ()
zone.js:199 Uncaught Error: Error: Received status '' for request to https://api.linkedin.com/v1/people/~?oauth_token=VjXSq40y5VTJGgFMBMYUpfm40CAfID0AI4hN
    at in.js:18
    at a (in.js:18)
    at in.js:18
    at MutationObserver.u (in.js:18)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:391)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runGuarded (zone.js:161)
    at MutationObserver.<anonymous> (zone.js:144)

**Comment by tuxd** [comment]
Oh that error is when I try to getUserInfo
