### ISSUE TITLE
getting error core.js:15723 ERROR TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by andola-dev** [NarHakobyan/ngx-linkedIn#2]
getting error in linked-in sign in
TypeError: Cannot read property 'then' of undefined

this.ngxLinkedinService.signIn().subscribe(user => {
console.info('signIn', user);
});

**Comment by andola-dev** [comment]
getting error in linked-in sign in
 TypeError: Cannot read property 'then' of undefined

this.ngxLinkedinService.signIn().subscribe(user => {
      console.info('signIn', user);
  });

**Comment by NarHakobyan** [comment]
@andola-dev hi, please send example application for this issue, thanks

**Comment by andola-dev** [comment]
Hi @NarHakobyan , please fine my code snippet below,

Installed ngx-linkedin via npm "npm install --save ngx-linkedin"

modified the app.module.ts file as below
```
import { NgxLinkedinModule } from 'ngx-linkedin';

imports: [
    ...
    NgxLinkedinModule.forRoot({
        clientId: '81ej875mxazqfw'
    }),
    .....]
```

in signin view file i have added a link with click event
```
<a type="button" class="btn-floating btn-li btn-sm" (click)="signInWithLinkedIn()">
                    <mdb-icon fab icon="linkedin"></mdb-icon>
                    </a>
```
In signin component i have used the below code
```
import { NgxLinkedinService } from 'ngx-linkedin';
export class SignInComponent implements OnInit {
public isAuthorized$ = this.ngxLinkedinService.isAuthorized();
constructor(
    private ngxLinkedinService: NgxLinkedinService
  ) { }

signInWithLinkedIn(): void {
    console.log("lllllll", this.isAuthorized$);
    this.ngxLinkedinService.signIn().subscribe(user => {
        console.info('signIn', user);
    });
  }
}
```

When i run the code & clicked on the linkedin login button it shows error 
```
core.js:15723 ERROR TypeError: Cannot read property 'then' of undefined
    at Object.authorize (in.js:18)
    at ngx-linkedin.js:198
    at new ZoneAwarePromise (zone.js:910)
    at NgxLinkedinService.push../node_modules/ngx-linkedin/fesm5/ngx-linkedin.js.NgxLinkedinService._authorize (ngx-linkedin.js:198)
    at SwitchMapSubscriber.project (ngx-linkedin.js:48)
    at SwitchMapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/switchMap.js.SwitchMapSubscriber._next (switchMap.js:35)
    at SwitchMapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (Subscriber.js:54)
    at TakeSubscriber.push../node_modules/rxjs/_esm5/internal/operators/take.js.TakeSubscriber._next (take.js:40)
    at TakeSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (Subscriber.js:54)
    at FilterSubscriber.push../node_modules/rxjs/_esm5/internal/operators/filter.js.FilterSubscriber._next (filter.js:38)
```

Please suggest how to fix this issue

**Comment by matheusmqar** [comment]
Keep getting this error too, have you found a way to fix it?

**Comment by NarHakobyan** [comment]
hi guys, this error comes from linkedIn sdk

**Comment by NarHakobyan** [comment]
closing for now.

**Comment by PRicardo** [comment]
How did you guys solve this problem?

**Comment by NarHakobyan** [comment]
It's nor solved, It's come from linkedIn sdk

**Comment by vishalamca** [comment]
Hi,

I am also getting the same error, is anyone aware how to fix the issue ?

Thanks,
Vishala

**Comment by ananbetak** [comment]
Even if it comes from linkedin , that doesn't mean that you should close and leave us.
if you want to build a library or want somebody to use it , you should consider explaining things better.
Thanks
