### ISSUE TITLE
Mixed Content

### ISSUE THREAD

**Issue by PRicardo** [NarHakobyan/ngx-linkedIn#3]
Hy guys!<br/> I'm dealing with an error that I know what is it, but don't know how to fix it. My app is using `HTPPS` protocol, but ngx-linkedIn makes a request to `http://platform.linkedin.com/in.js`, causing `Mixed Content` error. Is there a way to solve that? I'm really sorry, I'm new to front end development and have no idea about how can use `https://platform.linkedin.com/in.js` instead of `http://platform.linkedin.com/in.js`. Thanks a lot.

**Comment by NarHakobyan** [comment]
Hi, you can use ssl option.

NgxLinkedinModule.forRoot({ 
clientId: ':clientId:',
ssl: true
})
